name: omlanalysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    if: contains(github.event.head_commit.message, '[omlanalysis]')
    runs-on: ghcr.io/utnak/oml-dev:latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: ./gradlew build

      - name: Load
        run: ./gradlew load

      - name: Run Scripts
        run: quarto render script/analysis_matrix.qmd

      - name: Publish Docs
        uses: actions/upload-pages-artifact@v4
        with:
          path: script/**/*.html

  deploy:
    if: contains(github.event.head_commit.message, '[omlanalysis]')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Spec
        id: deployment
        uses: actions/deploy-pages@v4
